#!/bin/bash
/home/roo/data/anlaysis_revise/dataset2/evaladmix/evalAdmix/evalAdmix -plink /home/roo/data/anlaysis_revise/dataset2/dataset2 -fname /home/roo/data/anlaysis_revise/dataset2/admixture.2.P -qname /home/roo/data/anlaysis_revise/dataset2/admixture.2.Q -o /home/roo/data/anlaysis_revise/dataset2/evaladmix/K2.corres -P 30
//home/roo/data/anlaysis_revise/dataset2/evaladmix/evalAdmix/evalAdmix -plink /home/roo/data/anlaysis_revise/dataset2/dataset2 -fname /home/roo/data/anlaysis_revise/dataset2/admixture.3.P -qname /home/roo/data/anlaysis_revise/dataset2/admixture.3.Q -o /home/roo/data/anlaysis_revise/dataset2/evaladmix/K3.corres -P 30
/home/roo/data/anlaysis_revise/dataset2/evaladmix/evalAdmix/evalAdmix -plink /home/roo/data/anlaysis_revise/dataset2/dataset2 -fname /home/roo/data/anlaysis_revise/dataset2/admixture.4.P -qname /home/roo/data/anlaysis_revise/dataset2/admixture.4.Q -o /home/roo/data/anlaysis_revise/dataset2/evaladmix/K4.corres -P 30
/home/roo/data/anlaysis_revise/dataset2/evaladmix/evalAdmix/evalAdmix -plink /home/roo/data/anlaysis_revise/dataset2/dataset2 -fname /home/roo/data/anlaysis_revise/dataset2/admixture.5.P -qname /home/roo/data/anlaysis_revise/dataset2/admixture.5.Q -o /home/roo/data/anlaysis_revise/dataset2/evaladmix/K5.corres -P 30
/home/roo/data/anlaysis_revise/dataset2/evaladmix/evalAdmix/evalAdmix -plink /home/roo/data/anlaysis_revise/dataset2/dataset2 -fname /home/roo/data/anlaysis_revise/dataset2/admixture.6.P -qname /home/roo/data/anlaysis_revise/dataset2/admixture.6.Q -o /home/roo/data/anlaysis_revise/dataset2/evaladmix/K6.corres -P 30
/home/roo/data/anlaysis_revise/dataset2/evaladmix/evalAdmix/evalAdmix -plink /home/roo/data/anlaysis_revise/dataset2/dataset2 -fname /home/roo/data/anlaysis_revise/dataset2/admixture.7.P -qname /home/roo/data/anlaysis_revise/dataset2/admixture.7.Q -o /home/roo/data/anlaysis_revise/dataset2/evaladmix/K7.corres -P 30
/home/roo/data/anlaysis_revise/dataset2/evaladmix/evalAdmix/evalAdmix -plink /home/roo/data/anlaysis_revise/dataset2/dataset2 -fname /home/roo/data/anlaysis_revise/dataset2/admixture.8.P -qname /home/roo/data/anlaysis_revise/dataset2/admixture.8.Q -o /home/roo/data/anlaysis_revise/dataset2/evaladmix/K8.corres -P 30
/home/roo/data/anlaysis_revise/dataset2/evaladmix/evalAdmix/evalAdmix -plink /home/roo/data/anlaysis_revise/dataset2/dataset2 -fname /home/roo/data/anlaysis_revise/dataset2/admixture.9.P -qname /home/roo/data/anlaysis_revise/dataset2/admixture.9.Q -o /home/roo/data/anlaysis_revise/dataset2/evaladmix/K9.corres -P 30
/home/roo/data/anlaysis_revise/dataset2/evaladmix/evalAdmix/evalAdmix -plink /home/roo/data/anlaysis_revise/dataset2/dataset2 -fname /home/roo/data/anlaysis_revise/dataset2/admixture.10.P -qname /home/roo/data/anlaysis_revise/dataset2/admixture.10.Q -o /home/roo/data/anlaysis_revise/dataset2/evaladmix/K10.corres -P 30